package com.gst.immo.db;
// Generated Feb 20, 2016 1:55:06 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubqueryToExpose generated by hbm2java
 */
@Entity
@Table(name = "subquery_to_expose", catalog = "immo")
public class SubqueryToExpose implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private ExposeBase exposeBase;
	private SubQuery subQuery;
	private String status;
	private Date dateTime;

	public SubqueryToExpose() {
	}

	public SubqueryToExpose(ExposeBase exposeBase, SubQuery subQuery, String status, Date dateTime) {
		this.exposeBase = exposeBase;
		this.subQuery = subQuery;
		this.status = status;
		this.dateTime = dateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_expose_id", nullable = false)
	public ExposeBase getExposeBase() {
		return this.exposeBase;
	}

	public void setExposeBase(ExposeBase exposeBase) {
		this.exposeBase = exposeBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_subquery_id", nullable = false)
	public SubQuery getSubQuery() {
		return this.subQuery;
	}

	public void setSubQuery(SubQuery subQuery) {
		this.subQuery = subQuery;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, insertable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
